# Generated by Django 4.2.4 on 2023-11-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_service_user_alter_shop_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=100)),
                ('energy', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='price',
        ),
        migrations.CreateModel(
            name='ShopASIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('asic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.asic')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.shop')),
            ],
        ),
    ]
