# Generated by Django 4.2.4 on 2023-11-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_asic_remove_shop_arrival_date_remove_shop_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=100, verbose_name='Классификация')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.AlterField(
            model_name='asic',
            name='energy',
            field=models.CharField(max_length=100, verbose_name='Энергопотребление'),
        ),
        migrations.AlterField(
            model_name='asic',
            name='manufacturer',
            field=models.CharField(max_length=100, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='asic',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='asic',
            name='power',
            field=models.CharField(max_length=100, verbose_name='Мощность'),
        ),
        migrations.CreateModel(
            name='ShopAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used', models.BooleanField(default=False)),
                ('accessories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.accessories')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.shop')),
            ],
        ),
    ]
